# Generated by Django 3.1.7 on 2021-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('dayhour', models.DateField()),
                ('temp_now', models.TextField()),
                ('weather_now', models.TextField()),
                ('precipitation', models.TextField()),
                ('humidity', models.TextField()),
                ('wind', models.TextField()),
            ],
        ),
    ]
