# Generated by Django 3.1.7 on 2021-05-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_location', models.CharField(max_length=150, verbose_name='Місцезнаходження датчика')),
                ('date', models.DateField(verbose_name='Дата заміру')),
                ('time', models.TimeField(verbose_name='Час заміру')),
                ('temperature', models.SmallIntegerField(verbose_name='Температура')),
                ('sensor_name', models.CharField(max_length=150, verbose_name='Назва датчика')),
                ('sensor_model', models.CharField(max_length=150, verbose_name='Модель датчика')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherForecast',
        ),
    ]
